# -*- coding: utf-8 -*-
"""Taller_2_Phyton.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14a1IzZPCQCXG1FIWJ4D2YuYanAXBBxJi
"""

# Ejercicio 1,2,3: Manipulación de Listas, Determinando la Generación, Verificar Condiciones Especiales

def verificarEdad():
  generaciones = ["Silent Generation", "Baby boomers y Silver", "Generación X", "Millenials", "Generación Z"]
  anVali = 18
  anAct = 2024
  anMue = 1924
  nombre = input("Ingrese su nombre: ")
  anNac = int(input(f"{nombre}, ingrese su año de nacimiento: "))

  if anNac > anAct or anNac < anMue:
    return "Año de nacimiento no válido"

  edad = anAct - anNac
  noEdad = anVali - edad
  if edad >= anVali:
    print(f"¡Felicitaciones {nombre}, tienes {edad}!")
  else:
    print(f"Aún no tienes más de 18, te faltan {noEdad} año(s) para cumplir {anVali}")

  def generacion():
    if anNac >= 1930 and anNac <= 1948:
      print(f"Parece que eres de la {generaciones[0]}")
    elif anNac >= 1949 and anNac <= 1962:
      print(f"Parece que eres de la generación {generaciones[1]}")
    elif anNac >= 1963 and anNac <= 1977:
      print(f"Parece que eres de la {generaciones[2]}")
    elif anNac >= 1978 and anNac <= 1992:
      print(f"Parece que eres de la generación {generaciones[3]}")
    elif anNac >= 1993:
      print(f"Parece que eres de la {generaciones[4]}")
    else:
      print("Parece ser que no perteneces a ninguna generación.")


  def numRed():
    if edad % 10 == 0:
      print("¡Felicitaciones, tu edad es un número redondo!")
    else:
      print("No tienes una edad redonda")

  generacion()
  numRed()

verificarEdad()

# Ejercicio 4: Lista de Contactos

def function_padre():
    contactos = []

    def agregarContacto():
        contactoObjecto = {}
        nombreContacto = input("Ingrese el nombre del contacto: ")
        phoneContacto = input("Ingrese el télefono del contacto: ")
        contactoObjecto["nombre"] = nombreContacto
        contactoObjecto["phone"] = phoneContacto
        contactos.append(contactoObjecto)
        print(f"El contacto {nombreContacto} con télefono {phoneContacto} ha sido agregada.")

    def buscarContacto():
        contactoAlBuscar = input("Ingrese el contacto para buscar: ")
        contactoEmcontrado = False
        contactoIndex = 0
        for i, cont in enumerate(contactos, start=0):
            if cont["nombre"] == contactoAlBuscar:
                contactoEmcontrado = True
                contactoIndex = i
                break
        if(contactoEmcontrado):
          print(f"Nombre: {contactos[contactoIndex]['nombre']}, teléfono: {contactos[contactoIndex]['phone']}")
        else:
          print("El contacto no fue encontrado.")

    def mostrarContactos():
        if contactos:
            print("Los contactos son:")
            for cont in contactos:
                print(f"- Nombre:  {cont['nombre']}, teléfono: {cont['phone']}")
        else:
            print("No hay tareas.")

    def editarContacto():
      contactoAlBuscar = input("Ingrese el contacto para buscar: ")
      contactoEmcontrado = False
      contactoIndex = 0
      for i, cont in enumerate(contactos, start=0):
        if cont["nombre"] == contactoAlBuscar:
          contactoEmcontrado = True
          contactoIndex = i
          break
      if(contactoEmcontrado):
        print(f"Esta editando el contacto: {cont['nombre']}, teléfono: {cont['phone']}")
        nombreContacto = input("Ingrese el nuevo nombre del contacto: ")
        phoneContacto = input("Ingrese el nuevo telefono del contacto: ")
        contactos[contactoIndex]["nombre"] = nombreContacto
        contactos[contactoIndex]["phone"] = phoneContacto
        print(f"El contacto {cont['nombre']} ha sido actualizado.")
      else:
        print("El contacto no fue encontrado para editar.")

    return agregarContacto, buscarContacto, mostrarContactos, editarContacto

agregarContacto, buscarContacto, mostrarContactos, editarContacto = function_padre()

progranma = True
while True:
  print("\n¿Qué desea realizar?")
  print("1. Agregar un contacto")
  print("2. Mostrar todos los contactos")
  print("3. Buscar un contacto")
  print("4. Editar contacto")
  print("5. Salir")

  opcion = input("Seleccione una opción: ")
  if opcion == "1":
    agregarContacto()
  elif opcion == "2":
    mostrarContactos()
  elif opcion == "3":
    buscarContacto()
  elif opcion == "4":
    editarContacto()
  elif opcion == "5":
    print("Saliendo del programa...")
    break
  else:
    print("Opción no válida, por favor intente nuevamente.")

# Ejercicio 5: Organizando una Fiesta

def agregar_invitado(lista_invitados, nombre):
    lista_invitados.append(nombre)

def eliminar_invitado(lista_invitados, nombre):
    if nombre in lista_invitados:
        lista_invitados.remove(nombre)
    else:
        print("El invitado no está en la lista.")

def verificar_invitado(lista_invitados, nombre):
    return nombre in lista_invitados

def editar_invitado(lista_invitados, nombre_antiguo, nombre_nuevo):
    if nombre_antiguo in lista_invitados:
        index = lista_invitados.index(nombre_antiguo)
        lista_invitados[index] = nombre_nuevo
    else:
        print("El invitado no está en la lista.")


lista_invitados = []
while True:
    print("1. Agregar Invitado")
    print("2. Eliminar Invitado")
    print("3. Verificar Invitado")
    print("4. Editar Invitado")
    print("5. Salir")
    opcion = int(input("Elige una opción: "))

    if opcion == 1:
        nombre = input("Ingresa el nombre del invitado: ")
        agregar_invitado(lista_invitados, nombre)
    elif opcion == 2:
        nombre = input("Ingresa el nombre del invitado que quieres eliminar: ")
        eliminar_invitado(lista_invitados, nombre)
    elif opcion == 3:
        nombre = input("Ingresa el nombre del invitado que quieres verificar: ")
        if verificar_invitado(lista_invitados, nombre):
            print(f"{nombre} está en la lista de invitados.")
        else:
            print(f"{nombre} no está en la lista de invitados.")
    elif opcion == 4:
        nombre_antiguo = input("Ingresa el nombre del invitado que quieres editar: ")
        nombre_nuevo = input("Ingresa el nuevo nombre: ")
        editar_invitado(lista_invitados, nombre_antiguo, nombre_nuevo)
    elif opcion == 5:
        break
    else:
        print("Opción no válida.")